In [41]:
import pandas as pd # Importar la librería pandas para manipulación y análisis de datos.

In [42]:
# Configura la opción de visualización para mostrar todas las columnas del DataFrame, sin limitaciones.
pd.set_option('display.max_columns', None)

In [43]:
df = pd.read_csv('CSV/Netflix_Engagement_Dataset.csv', index_col=0)
df

Subscription Length (Months)  Customer Satisfaction Score (1-10)  \
Customer ID                                                                     
1                                      50                                  10   
2                                      40                                   5   
3                                      17                                   8   
4                                      59                                  10   
5                                       5                                   7   
...                                   ...                                 ...   
3496                                   20                                   4   
3497                                   56                                   8   
3498                                   52                                   7   
3499                                   34                                   5   
3500                                    6                                   5   

             Daily Watch Time (Hours)  Engagement Rate (1-10)  \
Customer ID                                                     
1                                4.32                       8   
2                                4.45                       3   
3                                4.81                       8   
4                                2.67                      10   
5                                4.20                       9   
...                               ...                     ...   
3496                             4.82                       6   
3497                             4.48                       7   
3498                             4.43                       8   
3499                             1.11                       3   
3500                             4.34                       3   

            Device Used Most Often Genre Preference         Region  \
Customer ID                                                          
1                           Mobile          Romance        Oceania   
2                         Smart TV           Comedy           Asia   
3                           Laptop           Sci-fi  South America   
4                           Mobile           Action         Africa   
5                         Smart TV           Sci-fi  North America   
...                            ...              ...            ...   
3496                        Laptop           Sci-fi           Asia   
3497                        Mobile          Romance         Africa   
3498                        Tablet           Sci-fi        Oceania   
3499                      Smart TV          Romance           Asia   
3500                        Mobile           Comedy  North America   

            Payment History (On-Time/Delayed) Subscription Plan  \
Customer ID                                                       
1                                     On-Time           Premium   
2                                     On-Time           Premium   
3                                     On-Time             Basic   
4                                     On-Time             Basic   
5                                     On-Time          Standard   
...                                       ...               ...   
3496                                  On-Time           Premium   
3497                                  On-Time             Basic   
3498                                  On-Time          Standard   
3499                                  On-Time             Basic   
3500                                  On-Time             Basic   

            Churn Status (Yes/No)  Support Queries Logged  Age  \
Customer ID                                                      
1                              No                       9   26   
2                              No                       6   27   
3                              No                       0   55   


In [44]:
df['Payment History (On-Time/Delayed)'].unique()

array(['On-Time', 'Delayed'], dtype=object)

In [45]:
# Mostrar las columnas del DataFrame `df` para ver los nombres de las columnas presentes en el dataset.
df.columns  

Index(['Subscription Length (Months)', 'Customer Satisfaction Score (1-10)',
       'Daily Watch Time (Hours)', 'Engagement Rate (1-10)',
       'Device Used Most Often', 'Genre Preference', 'Region',
       'Payment History (On-Time/Delayed)', 'Subscription Plan',
       'Churn Status (Yes/No)', 'Support Queries Logged', 'Age',
       'Monthly Income ($)', 'Promotional Offers Used',
       'Number of Profiles Created'],
      dtype='object')

In [46]:
print(df.info())  # Información general sobre las columnas y tipos de datos del DataFrame de vuelos.

<class 'pandas.core.frame.DataFrame'>
Index: 3500 entries, 1 to 3500
Data columns (total 15 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   Subscription Length (Months)        3500 non-null   int64  
 1   Customer Satisfaction Score (1-10)  3500 non-null   int64  
 2   Daily Watch Time (Hours)            3500 non-null   float64
 3   Engagement Rate (1-10)              3500 non-null   int64  
 4   Device Used Most Often              3500 non-null   object 
 5   Genre Preference                    3500 non-null   object 
 6   Region                              3500 non-null   object 
 7   Payment History (On-Time/Delayed)   3500 non-null   object 
 8   Subscription Plan                   3500 non-null   object 
 9   Churn Status (Yes/No)               3500 non-null   object 
 10  Support Queries Logged              3500 non-null   int64  
 11  Age                                 3500 non-nul

In [47]:
df.duplicated().sum()  # Verificar si existen filas duplicadas en el DataFrame de vuelos.

np.int64(0)

In [48]:
df.isnull().sum() # Verificar si existen valores nulos en el DataFrame de vuelos.

Subscription Length (Months)          0
Customer Satisfaction Score (1-10)    0
Daily Watch Time (Hours)              0
Engagement Rate (1-10)                0
Device Used Most Often                0
Genre Preference                      0
Region                                0
Payment History (On-Time/Delayed)     0
Subscription Plan                     0
Churn Status (Yes/No)                 0
Support Queries Logged                0
Age                                   0
Monthly Income ($)                    0
Promotional Offers Used               0
Number of Profiles Created            0
dtype: int64

In [49]:
df.describe().T # Estadísticas descriptivas de las columnas numéricas del DataFrame de vuelos.

count         mean          std     min  \
Subscription Length (Months)        3500.0    30.538000    17.259100     1.0   
Customer Satisfaction Score (1-10)  3500.0     6.929714     2.666824     1.0   
Daily Watch Time (Hours)            3500.0     3.509451     1.441229     1.0   
Engagement Rate (1-10)              3500.0     6.954286     2.671427     1.0   
Support Queries Logged              3500.0     5.023714     3.149011     0.0   
Age                                 3500.0    43.868286    15.323885    18.0   
Monthly Income ($)                  3500.0  5491.886857  2575.005711  1010.0   
Number of Profiles Created          3500.0     3.018857     1.412875     1.0   

                                        25%      50%      75%     max  
Subscription Length (Months)          16.00    31.00    45.00    60.0  
Customer Satisfaction Score (1-10)     5.00     8.00     9.00    10.0  
Daily Watch Time (Hours)               2.25     3.51     4.74     6.0  
Engagement Rate (1-10)                 5.00     8.00     9.00    10.0  
Support Queries Logged                 2.00     5.00     8.00    10.0  
Age                                   30.00    44.00    57.00    70.0  
Monthly Income ($)                  3282.00  5513.00  7729.00  9990.0  
Number of Profiles Created             2.00     3.00     4.00     5.0

In [50]:
df.round(2) # Redondear a dos decimales la columna 'Daily Watch Time (Hours)'.

Subscription Length (Months)  Customer Satisfaction Score (1-10)  \
Customer ID                                                                     
1                                      50                                  10   
2                                      40                                   5   
3                                      17                                   8   
4                                      59                                  10   
5                                       5                                   7   
...                                   ...                                 ...   
3496                                   20                                   4   
3497                                   56                                   8   
3498                                   52                                   7   
3499                                   34                                   5   
3500                                    6                                   5   

             Daily Watch Time (Hours)  Engagement Rate (1-10)  \
Customer ID                                                     
1                                4.32                       8   
2                                4.45                       3   
3                                4.81                       8   
4                                2.67                      10   
5                                4.20                       9   
...                               ...                     ...   
3496                             4.82                       6   
3497                             4.48                       7   
3498                             4.43                       8   
3499                             1.11                       3   
3500                             4.34                       3   

            Device Used Most Often Genre Preference         Region  \
Customer ID                                                          
1                           Mobile          Romance        Oceania   
2                         Smart TV           Comedy           Asia   
3                           Laptop           Sci-fi  South America   
4                           Mobile           Action         Africa   
5                         Smart TV           Sci-fi  North America   
...                            ...              ...            ...   
3496                        Laptop           Sci-fi           Asia   
3497                        Mobile          Romance         Africa   
3498                        Tablet           Sci-fi        Oceania   
3499                      Smart TV          Romance           Asia   
3500                        Mobile           Comedy  North America   

            Payment History (On-Time/Delayed) Subscription Plan  \
Customer ID                                                       
1                                     On-Time           Premium   
2                                     On-Time           Premium   
3                                     On-Time             Basic   
4                                     On-Time             Basic   
5                                     On-Time          Standard   
...                                       ...               ...   
3496                                  On-Time           Premium   
3497                                  On-Time             Basic   
3498                                  On-Time          Standard   
3499                                  On-Time             Basic   
3500                                  On-Time             Basic   

            Churn Status (Yes/No)  Support Queries Logged  Age  \
Customer ID                                                      
1                              No                       9   26   
2                              No                       6   27   
3                              No                       0   55   


In [51]:
df['Daily Watch Time (Hours)']

Customer ID
1       4.32
2       4.45
3       4.81
4       2.67
5       4.20
        ... 
3496    4.82
3497    4.48
3498    4.43
3499    1.11
3500    4.34
Name: Daily Watch Time (Hours), Length: 3500, dtype: float64

In [52]:
df['Customer Satisfaction Score (1-10)'].unique() # Verificar los valores únicos presentes en la columna 'Customer Satisfaction Score (1-10)'.

array([10,  5,  8,  7,  9,  4,  2,  6,  3,  1])

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3500 entries, 1 to 3500
Data columns (total 15 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   Subscription Length (Months)        3500 non-null   int64  
 1   Customer Satisfaction Score (1-10)  3500 non-null   int64  
 2   Daily Watch Time (Hours)            3500 non-null   float64
 3   Engagement Rate (1-10)              3500 non-null   int64  
 4   Device Used Most Often              3500 non-null   object 
 5   Genre Preference                    3500 non-null   object 
 6   Region                              3500 non-null   object 
 7   Payment History (On-Time/Delayed)   3500 non-null   object 
 8   Subscription Plan                   3500 non-null   object 
 9   Churn Status (Yes/No)               3500 non-null   object 
 10  Support Queries Logged              3500 non-null   int64  
 11  Age                                 3500 non-nul

In [54]:
df['Engagement Rate (1-10)'].unique() # Verificar los valores únicos presentes en la columna 'Engagement Rate (1-10)'.

array([ 8,  3, 10,  9,  5,  7,  4,  1,  6,  2])

In [55]:
df['Genre Preference'].unique() # Verificar los valores únicos presentes en la columna 'Genre Preference'.

array(['Romance', 'Comedy', 'Sci-fi', 'Action', 'Drama'], dtype=object)

In [56]:
df['Region'].unique() # Verificar los valores únicos presentes en la columna 'Region'.

array(['Oceania', 'Asia', 'South America', 'Africa', 'North America',
       'Europe'], dtype=object)

In [57]:
df['Subscription Plan'].unique() # Verificar los valores únicos presentes en la columna 'Subscription Plan'.

array(['Premium', 'Basic', 'Standard'], dtype=object)

In [58]:
df['Churn Status (Yes/No)'].unique() # Verificar los valores únicos presentes en la columna 'Churn Status (Yes/No)'.

array(['No', 'Yes'], dtype=object)

In [59]:
df['Monthly Income ($)'].unique()

array([3307, 7333, 7527, ..., 9579, 6914, 6525], shape=(2920,))

In [60]:
df['Promotional Offers Used'].unique()

array(['Yes', 'No'], dtype=object)

In [61]:
df['Payment History (On-Time/Delayed)'].unique()

array(['On-Time', 'Delayed'], dtype=object)

In [62]:
df = df.drop(columns=['Promotional Offers Used'])

In [63]:
df = df.rename(columns={
    'Customer ID': 'ID Cliente',
    'Subscription Length (Months)': 'Duracion de la Suscripcion (Meses)',
    'Customer Satisfaction Score (1-10)': 'Satisfaccion del Cliente (1-10)',
    'Daily Watch Time (Hours)': 'Tiempo de Visualizacion Diario (Horas)',
    'Engagement Rate (1-10)': 'Indice de Compromiso (1-10)',
    'Device Used Most Often': 'Dispositivo mas Usado',
    'Genre Preference': 'Genero Preferido',
    'Region': 'Region',
    'Payment History (On-Time/Delayed)': 'Historial de Pago (A Tiempo/Retrasado)',
    'Subscription Plan': 'Plan de Suscripcion',
    'Churn Status (Yes/No)': 'Estado de Cancelacion (Sí/No)',
    'Support Queries Logged': 'Consultas al Soporte',
    'Age': 'Edad',
    'Monthly Income ($)': 'Ingresos Mensuales ($)',
    'Number of Profiles Created': 'Numero de Perfiles Creados'
})

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3500 entries, 1 to 3500
Data columns (total 14 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Duracion de la Suscripcion (Meses)      3500 non-null   int64  
 1   Satisfaccion del Cliente (1-10)         3500 non-null   int64  
 2   Tiempo de Visualizacion Diario (Horas)  3500 non-null   float64
 3   Indice de Compromiso (1-10)             3500 non-null   int64  
 4   Dispositivo mas Usado                   3500 non-null   object 
 5   Genero Preferido                        3500 non-null   object 
 6   Region                                  3500 non-null   object 
 7   Historial de Pago (A Tiempo/Retrasado)  3500 non-null   object 
 8   Plan de Suscripcion                     3500 non-null   object 
 9   Estado de Cancelacion (Sí/No)           3500 non-null   object 
 10  Consultas al Soporte                    3500 non-null   int64  
 

In [65]:
# Guardar el DataFrame combinado en un archivo CSV.
df.to_csv("CSV/Netflix_Engagement.csv", index=False) # index=False evita que se guarde el índice.

In [66]:
df['Numero de Perfiles Creados'].unique()

array([2, 3, 4, 5, 1])

Number of Profiles Created con Age 

Device Used Most Often con Age

Daily Watch Time (Hours) con Age

Genre Preference con Age

Subscription Plan con Age

Subscription Plan con Number of Profiles Created

Customer Satisfaction Score (1-10) con 	Region

Customer Satisfaction Score (1-10) con Subcription Plan

Customer Satisfaction Score (1-10) con Daily Watch Time (Hours)

Customer Satisfaction Score (1-10) con Age

Monthly Income ($) con Daily Watch Time (Hours)

Monthly Income ($) con Age

Region con Daily Watch Time (Hours)

Promotional Offers Used con Subscription Length (Months)

Monthly Income ($) con Number of Profiles Created

Genre Preference con Daily Watch Time (Hours)

Engagement Rate (1-10) con 

Churn Status (Yes/No) con Subscription Plan

Churn Status (Yes/No) con Number of Profiles Created

Churn Status (Yes/No) con Daily Watch Time (Hours)

Payment History (On-Time/Delayed) con Age

Support Queries Logged con Customer Satisfaction Score (1-10)

Support Queries Logged con Region

Region con Payment History (On-Time/Delayed)

Subscription Length (Months) con Region

Subscription Length (Months) con Customer Satisfaction Score (1-10)

Subscription Length (Months) con Subscription Plan

Subscription Length (Months) con Support Queries Logged

Subscription Length (Months) con Age

Subscription Length (Months) con Monthly Income ($)